# -*- coding: utf-8 -*-
"""建立/更新 SlimeCat 遊戲工廠的生產排程（2026-09-05 起：每週六 02:00 一款）。

做兩件事：
  1. 產生 run_factory.bat
     （CRLF＋純 ASCII＋python 絕對路徑 —— Windows 排程器的三個地雷都避開；
      內含心跳檔與 factory.log 輪轉，這支腳本是 bat 的唯一來源，別直接改 bat）
  2. schtasks 建立每週 RUN_DAY RUN_AT 的排程（重跑本腳本 = 更新設定，冪等）

任務名稱保留 "SlimeCat Factory Daily"（produce_now.py 引用它觸發加產，改名會牽連）。
沿革：每日 12:00（7/4）→ 每 3 天 12:00（8/9）→ 每週六 02:00（9/5 Boss 拍板 1C，一週一款做大做好）。
"""
import subprocess
import sys
from pathlib import Path

sys.stdout.reconfigure(encoding="utf-8")

ROOT = Path(__file__).resolve().parent.parent
BAT = ROOT / "run_factory.bat"
TASK_NAME = "SlimeCat Factory Daily"
RUN_DAY = "SAT"      # 每週幾生產（schtasks /D 代碼：MON..SUN）
RUN_AT = "02:00"     # 凌晨跑：撞額度也有一整天可以自動補跑，白天不跟 Boss 搶額度

PYTHON = sys.executable  # 真實 python 絕對路徑（不能用 WindowsApps 假捷徑）


def write_bat() -> None:
    make_game = ROOT / "factory" / "make_game.py"
    logf = ROOT / "factory" / "factory.log"
    hb = ROOT / "factory" / "factory_heartbeat.txt"
    lines = [
        "@echo off",
        "chcp 65001 >nul",
        "REM Generated by factory/setup_schedule.py - edit that script, not this file.",
        "REM Heartbeat marker for _common/heartbeat.py (health check 2026-09 backlog level 1, item 4):",
        "REM factory.log is shared with run_feedback.bat / run_weekly.bat, so its mtime stays fresh even",
        "REM when production has stopped for weeks. Only THIS factory run touches factory_heartbeat.txt.",
        "REM Redirection goes FIRST on the echo lines: a trailing digit before > (exit 0>>) would be",
        "REM parsed by cmd as a file-handle redirect and silently break the marker.",
        "REM Rotate factory.log past 2MB (health check 2026-09 backlog level 3): all five factory scripts",
        "REM append to it and nothing ever rotated it. Must happen HERE before python starts, because this",
        "REM bat redirects python stdout into the same file (an in-process rename would hit \"file in use\").",
        f"set LOGF={logf}",
        'if exist "%LOGF%" for %%A in ("%LOGF%") do if %%~zA GTR 2097152 move /y "%LOGF%" "%LOGF%.old" >nul',
        f"set HB={hb}",
        '> "%HB%" echo %date% %time% start',
        f'"{PYTHON}" "{make_game}" >> "%LOGF%" 2>&1',
        "set RC=%ERRORLEVEL%",
        '>> "%HB%" echo %date% %time% exit %RC%',
        "exit /b %RC%",
        "",
    ]
    BAT.write_bytes("\r\n".join(lines).encode("ascii"))
    print(f"✅ 已寫 {BAT}")


def create_task() -> int:
    # /SC WEEKLY /D SAT ＝ 每週六；/ST 02:00
    cmd = ["schtasks", "/Create", "/TN", TASK_NAME, "/TR", str(BAT),
           "/SC", "WEEKLY", "/D", RUN_DAY, "/ST", RUN_AT, "/F"]
    proc = subprocess.run(cmd, capture_output=True)
    out = (proc.stdout + proc.stderr).decode("cp950", errors="replace").strip()
    print(out)
    if proc.returncode == 0:
        print(f"✅ 排程「{TASK_NAME}」已建立：每週 {RUN_DAY} {RUN_AT} 自動生一款新遊戲")
        print(f'   暫停生產：schtasks /Change /TN "{TASK_NAME}" /Disable')
        print(f'   立刻生一款：schtasks /Run /TN "{TASK_NAME}"')
    return proc.returncode


if __name__ == "__main__":
    write_bat()
    sys.exit(create_task())
